# How many distinct terms are in the sequence
# generated by a^b for 2<= a <=100 and 2 <= b <= 100?

MAX = 100
seq = []
for a in range(2, MAX + 1):
    for b in range(2, MAX + 1):
        seq.append(a**b)
seq.sort()
result = len(seq)
j = 0
for i in range(len(seq)):
    if seq[i] != seq[j]:
        result -= i-j-1
        j = i
print result


